# https://simonwillison.net/2020/Oct/9/git-scraping/

name: Scrape actual establishments data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |-
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Scrape actual data
      run: |-
        python3 -m foodpillory.facilities
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest actual data: ${timestamp}" || exit 0
        git push
